apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/gke-django-tutorial/frontend:latest
          imagePullPolicy: Always
          command: ["npm", "start"]
          ports:
          - containerPort: 3000
