# docker-compose.yml
version: "3.7"

services:
  frontend:
    build: .
    volumes:
      - .:/code
      - /code/node_modules
    ports:
      - "3000:3000"
    command: yarn start
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
